### ISSUE TITLE
deployment as currently described in the README does not work

### ISSUE THREAD

**Issue by axb21** [gama-platform/gama.cloud#17]
I have attempted to download and run gama.cloud using the instructions described in the README. Neither the standalone nor the tomcat deployment instructions have worked for me. I am using Kubuntu 20.04 and downloaded the only currently-available release, as linked in the README.

When attempting to run with the embedded tomcat version, firstly the `gama.sh` script does not work. There is a dot backslash between `-jar` and `gamaweb.jar` in the script that should not be there.. A corrected version is:
```bash
java -jar gamaweb.jar controller_GamaWeb 8080 127.0.0.1:8080
```

In my environment, the above complains about a problem with the user preferences directory, but seems to launch. However, the URL `http://localhost:8080/GamaWeb/texteditor` returns a 404 error.

I also attempted to deploy in tomcat, using tomcat version 9.0.37. GamaWeb does not work in this scenario either, also returning a 404 error. The tomcat admin GUI shows that the WAR file has been deployed. However, the link given in the README does not lead to the editor. I have not been able to deduce what, if any, is the correct URL to use.

At this time, GamaWeb appears to be broken beyond use, at least on my machine/setup. I would like to try it so any help is appreciated. Please let me know if I can supply any further information or test anything.

Two other observations: 
* I was not able to run the JAR file on the command line with any version of java before version 15. I am not sure if this is intentional but it's a fairly big constraint; these days most folks try to target java 8.
* The screen captures in the README show a web browser pointing to `http://127.0.0.1:10080/texteditor`, which is different from the URL the README says to hit. That URL doesn't work either, but it's confusing that the screen captures and README text are not in sync.

**Comment by hqnghi88** [comment]
HI,
Thanks to test all the things. 
Sorry for the syntax in the sh script. I forgot to update. The syntax is as same as what you have corrected, the meaning of parameter after gama.jar is the path for routing on web. So if you want to use http://localhost:8080/GamaWeb/texteditor, you should run:

java -jar gamaweb.jar GamaWeb 8080 127.0.0.1:8080

And the release is currently built with jdk 15

**Comment by hqnghi88** [comment]
sorry, the right url is (remove the texteditor) :  http://localhost:8080/GamaWeb/

**Comment by axb21** [comment]
Thank you for your quick response! I think there is something else wrong, though. 

Here is a screenshot from my browser after starting GamaWeb by copy-pasting the command from your comment:
![image](https://user-images.githubusercontent.com/3464572/116697752-9039ef00-a991-11eb-9e63-f04ab8adf69f.png)

Here are a few lines of my console output:
```
me@machine:~/Downloads/GamaWeb$ java -jar gamaweb.jar GamaWeb 8080 127.0.0.1:8080  
2021-04-30 08:50:57.969:INFO::main: Logging initialized @83ms to org.eclipse.jetty.util.log.StdErrLog
tmpPath /home/abucci/Downloads/GamaWeb/GamaWeb_tmp_
2021-04-30 08:50:58.030:INFO:oejs.Server:main: jetty-9.4.37.v20210219; built: 2021-02-19T15:16:47.689Z; git: 27afab2bd37780d179836e313e0fe11bc4fa0ce9; jvm 15+36-Ubuntu-1
2021-04-30 08:50:58.252:INFO:oejw.StandardDescriptorProcessor:main: NO JSP Support for /GamaWeb, did not find org.eclipse.jetty.jsp.JettyJspServlet
2021-04-30 08:50:58.265:INFO:oejs.session:main: DefaultSessionIdManager workerName=node0
2021-04-30 08:50:58.265:INFO:oejs.session:main: No SessionScavenger set, using defaults
2021-04-30 08:50:58.266:INFO:oejs.session:main: node0 Scavenging every 600000ms
xxxxxxxxxxxxxxx                xxx
xxxxxxxxxxxxxxx                xxx
xxxxxxxxxxxxxxx                xxx
xxxxxxxxxxxxxxx                xxx
/etc/.java/.uprefs
/etc/.java/.sprefs
> JAI/ImageIO subsystem activated to read [, jpg, tiff, bmp, gif, arx, tf8, TF8, png, ppm, jp2, tif, TIF, asc, TIFF, btf, BTF, pgm, wbmp, jpeg, pbm]
Apr 30, 2021 8:51:00 AM java.util.prefs.FileSystemPreferences$1 run
```

I am unsure what to try next, but it does not work for me.

**Comment by axb21** [comment]
Oh, I have it working now! It appears that the errors I was getting about the user preferences are critical. Gama will not launch properly until those are resolved. I did the obviously horrible test of running the JAR as root, and it works fine. So this is a configuration issue on my side.

@hqnghi88's clarifying comment is important--I followed the instructions in their comment, not what was on the README when I started this. Thank you for your help!

**Comment by hqnghi88** [comment]
![20210430_203539](https://user-images.githubusercontent.com/6105384/116702950-e3dd2480-a9f3-11eb-9240-f3f7ee490171.jpg)
Just missing a sudo , i think

**Comment by vbaryshev** [comment]
Hello!
GAME cloud game not received according to instructions **(Apache Tomcat/8.5.78) JDK 8**.
HTTP Status 404 - Not Found
Type Status Report

Message The requested resource [/GamaWeb/] is not available

Description The origin server did not find a current representation for the target resource or is not willing to disclose that one exists.
**Apache Tomcat/8.5.78**

configuration **gama.bat**: 
start java -jar gamaweb.jar GamaWeb 8080 127.0.0.1:8080
rem start file://%cd%/index.html

configuration **gama.sh**: 
java -jar gamaweb.jar GamaWeb 8080 127.0.0.1:8080

Thanks for the answer!
