### ISSUE TITLE
msi.gama.lang.gaml.web contains compilation error

### ISSUE THREAD

**Issue by benoitgaudou** [gama-platform/gama.cloud#6]
The plugin msi.gama.lang.gaml.web, Class GamlLabelProvider.java contains a compilation error: 
		if (ele.getBlock() != null && ele.getBlock().getFunction() != null) {

Benoit

**Comment by hqnghi88** [comment]
The commit in Friday midnight, do you remember it? It affect grammar, i am adapting it
